# Generated by Django 4.1.1 on 2022-12-17 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inscritos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=15)),
                ('fechaInscripcion', models.DateField()),
                ('institucion', models.CharField(max_length=50)),
                ('horaInscripcion', models.CharField(max_length=10)),
                ('estado', models.CharField(max_length=20)),
                ('observacion', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('codigo', models.IntegerField()),
                ('direccion', models.CharField(max_length=50)),
            ],
        ),
    ]
